---
- hosts: all
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repo'
    raw: 'apt-get update'
  - name: 'Instalando o Python'
    raw: 'apt-get install -y python'
  roles:
    - install_k8s_role

- hosts: k8s-master
  roles:
    - create_cluster_role

- hosts: k8s-worker
  roles:
    - join_workers_role